### PR TITLE
modify 'auto-config' configuration  #201

### PR DESCRIPTION
**Pull request by btsatoutkzy**
Please review #201.

### CODE REVIEW

**Comment by btshimizukza** [comment]
@btsatoutkzy 

Please resolve conflicts.

**Comment by btsatoutkzy** [comment]
@btshimizukza

resolve conflicts. #201

**Comment by kazuki43zoo** [comment]
@btsatoutkzy 

please resolve #207 via this PR.

**Comment by btsatoutkzy** [comment]
@btshimizukza
add  <sec:logout/> #201.

**Comment by btsatoutkzy** [comment]
modify 'sec:logout' position #201.

**Pull request merged**
